<a href="https://colab.research.google.com/github/JunHL96/pythonTutorial/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. Pytorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/




In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


### If Apple Silicon User:

In [ ]:
mps = torch.device("mps") if torch.backends.mps.is_available() else torch.device("cpu")
print(f"MPS Available: {torch.backends.mps.is_available()}")

## Introduction to Tensors


### What are tensors?

A tensor is a multi-dimensional matrix containing elements of a single data type.

### Creating tensors

PyTorch tensors are created using 'torch.tensor()' = https://pytorch.org/docs/stable/tensors.html



In [21]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [22]:
scalar.ndim

0

In [23]:
# Get tensor back as Python int
scalar.item()

7

In [24]:
# Vector (magnitude, direction)
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [25]:
vector.ndim

1

In [26]:
vector.shape

torch.Size([2])

## Matrix

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])


In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape # torch.Size([2, 2]) which means 2x2 or 2 by 2

torch.Size([2, 2])


<details>

### `.shape`
- **Returns the dimensions of the tensor (or array)** as a tuple.
- Each element of the tuple (an ordered, immutable collection of items) represents the size of the tensor in that dimension.

Example:
```python
vector = torch.tensor([7, 7])
print(vector.shape)  # Output: torch.Size([2])
```

### `.ndim`
- **Returns the number of dimensions (rank) of the tensor.**
- this is an integer value representing how many dimensions the tensor has

Example:
```python
vector = torch.tensor([7, 7])
print(vector.ndim)  # Output: 1
```

### Explanation:
- `vector = torch.tensor([7, 7])` creates a 1D tensor (vector) with 2 elements.
- `.shape` gives `(2)` because the vector has 2 elements in one dimension.
- `.ndim` gives `1` because the tensor is 1-dimensional.


| Attribute  | Description                               | Example Output            |
|------------|-------------------------------------------|---------------------------|
| `.shape`   | Tuple representing the size of each dimension | `torch.Size([2])`   |
| `.ndim`    | Integer representing the number of dimensions | `1`                       |

</details>

## Tensors


In [15]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape # the result is torch.Size([1, 3, 3]), meaning we have one 3x3 tensor

torch.Size([1, 3, 3])

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Image Representation
https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png

## Random Tensors

### Why Random Tensors?
Random tensors are important b/c the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

### Documentation of torch.rand
https://pytorch.org/docs/stable/generated/torch.rand.html


In [28]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7278, 0.1392, 0.7996, 0.5772],
        [0.3312, 0.4162, 0.4788, 0.0087],
        [0.5723, 0.9869, 0.0438, 0.7506]])

In [29]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

### Zeroes and Ones Tensors

In [30]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
random_tensor.dtype # check data type of our random tensor

torch.float32